{% set name = "dbt-duckdb" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt-duckdb-{{ version }}.tar.gz
  sha256: e36776d6ee7aa1554a236b7ffa93c556c4419920134a3801feef7c64b706db16

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - dbt-core >=1.6.0,<1.7
    - python-duckdb >=0.7.0

test:
  imports:
    - dbt
    - dbt.adapters.duckdb
    - dbt.adapters.duckdb.environments
    - dbt.adapters.duckdb.plugins
    - dbt.include.duckdb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jwills/dbt-duckdb
  summary: The duckdb adapter plugin for dbt (data build tool)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AlexanderThebeltQC
    - SaravananSathyanandhaQC
